version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./frontend_startup.sh

    expose:
      - 8890

    ports:

      - 8890:8890

volumes:
  static_volume:
