version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./frontend_startup.sh
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    expose:
      - 8890
    ports:
      - 8890:8890
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  static_volumes:
