version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./frontend_startup.sh
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    expose:
      - 8890

    ports:

      - 8890:8890

volumes:
  static_volume:
